# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MailWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MailWeather

  target 'MailWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MailWeatherUITests' do
    # Pods for testing
  end

end
